export const SERVICES = {
  AUTH: {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT'
  },

  LEAFLET: {
    FIND_PROJECT_LAYER_BY_POLYGON_ID: 'FIND_PROJECT_LAYER_BY_POLYGON_ID',
    DELETE_LAYER: 'DELETE_LAYER',
    VIEW_LAYER: 'VIEW_LAYER',
    VIEW_PROJECT_LAYER: 'VIEW_PROJECT_LAYER',
    GET_LAYERS: 'GET_LAYERS',
    GET_LAYERS_IDS: 'GET_LAYERS_IDS',
    FETCH_PROJECT_LAYERS: 'FETCH_PROJECT_LAYERS',
    HIGHLIGHT_LAYER: 'HIGHLIGHT_LAYER',
    SET_BOUNDS: 'SET_BOUNDS',
    highLightStyles: {
      fillColor :'cyan'
    }
  }
}
