export const polygonAPI = 'polygon'
export const projectAPI = 'project'
export const viewsAPI = 'view'
export const satelitalImageAPI = 'satelital_image'
export const satelitalIndexAPI = 'satelital_index'
export const portalAPI = 'portal'
export const calculatorAPI = 'calculator'
